#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Yushi"
email = "yushi_61@proton.me"

[ui]
default-command = "log"
editor = "nvim"
diff-editor = ":builtin"
diff-formatter = ":git"
pager = "less -FRX"
graph.style = "curved"

[git]
colocate = true
sign-on-push = true

[signing]
behavior = "own"
backend = "gpg"
key = "B00996246A9FB926"

[template-aliases]
"format_short_id(id)" = "id.shortest(8)"

[revsets]
'mine()' = 'author(yushi_61)'
