#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Yushi"
email = "yushi_61@proton.me"

[ui]
default-command = "log"
editor = "nvim"
diff-editor = ":meld"
merge-editor = ":meld"
pager = "less -FRX"

[git]
private-commits = "description-or-title"

[signing]
backend = "gpg"
key = "B00996246A9FB926"

[core]
fsmonitor = "watchman"

[template-aliases]
"format_short_id(id)" = "id.shortest(12)"
"format_timestamp(timestamp)" = "timestamp.utc().format(\"%Y-%m-%d %H:%M:%S\")"

[revsets]
"log-limit = "200"
